[package]
name = "parenchyma"
version = "0.1.0"
authors = ["Jony <jonysy@users.noreply.github.com>"]
keywords = ["backend", "computation", "opencl", "cuda", "hpc", "high-performance-computing"]
categories = []
license = "MIT/Apache-2.0"

[workspace]
members = ["./frameworks/native"]